apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-app
  labels:
    app: flask-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      
  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
      - name: flask-app
        image: python:3.11.7-alpine
        ports:
        - containerPort: 8080
      imagePullSecrets:
---
apiVersion: v1
kind: Service

metadata:
  name: flask-app-service

spec:
  selector:
    app: flask-app

 # type: LoadBalancer

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
 #     nodePort: 30000
