apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2h1Yi5kb2NrZXIuY29tL3UvbXN1cmoiOnsidXNlcm5hbWUiOiJtc3VyaiIsInBhc3N3b3JkIjoiVjd2ZXJzYWNlIiwiZW1haWwiOiJzYWlmLm1zcmpAZ21haWwuY29tIiwiYXV0aCI6ImJYTjFjbW82VmpkMlpYSnpZV05sIn19fQ==
kind: Secret
metadata:
  creationTimestamp: "2023-12-06T23:42:21Z"
  name: regcred
  namespace: default
  resourceVersion: "25960"
  uid: 4303780e-8307-4414-bb5d-639068828baf
type: kubernetes.io/dockerconfigjson